site_name: eangius-pyutils
site_url: https://eangius.github.io/pyutils/
repo_url: https://github.com/eangius/pyutils/
copyright: Copyright &copy; <a href="https://github.com/eangius">eangius</a>.


theme:
  name: readthedocs
  locale: en
  features:
    - navigation.indexes

plugins:
  - mkdocstrings
  - search

nav:
  - About: 'index.md'
  - References:
    - 'api_multimap.md'
  - Examples: 'examples.md'


validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
